name: Build & Flash Pico

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  flash:
    name: Build, Flash & UART
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "PICO_SDK_PATH=$HOME/pico-sdk" >> "$GITHUB_ENV"
          echo "PICO_BOARD=pico" >> "$GITHUB_ENV"

      - name: Configure & build
        run: |
          cmake -S . -B build \
            -DPICO_SDK_PATH="$PICO_SDK_PATH" \
            -DPICO_BOARD="$PICO_BOARD"
          cmake --build build -- -j"$(nproc)"

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-firmware
          path: build/*.uf2

      - name: Flash firmware
        timeout-minutes: 3
        run: |
          set -euo pipefail
          sudo picotool reboot -f -u || true
          sleep 5
          picotool info
          sleep 10
          sudo picotool load --force -v build/main.uf2
          picotool reboot -f || true

      - name: Capture UART output
        run: |
          set -euo pipefail
          for i in {1..50}; do
            [ -e /dev/ttyACM0 ] && break || sleep 0.2
          done
          stty -F /dev/ttyACM0 raw 115200 -echo
          echo "::group::UART Output"
          timeout 30s cat /dev/ttyACM0 || true
          echo "::endgroup::"

      - name: Summary
        run: echo "✅ Completed on $HOSTNAME"
